on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build package
      run: |
        dotnet restore
        dotnet sonarscanner begin \
          /o:cuteribs \
          /k:cuteribs_autorest-legacy \
          /d:sonar.host.url=https://sonarcloud.io
          
        dotnet build --no-restore
          
        dotnet sonarscanner end
        
      
      
      
  
